/*
Copyright (c) 2012-2016 Daniel Burke

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

   1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.

   2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.

   3. This notice may not be removed or altered from any source
   distribution.
*/
#ifdef __APPLE__
#include <OpenGL/gl.h>
#else
#include <GL/glew.h>
#endif

#include "version.h"	/* generated by make from git */
#include "main.h"

#include <stdio.h>
long long time_start = 0;
float time = 0;


int main_init(int argc, char *argv[])
{
	printf("Version    : %s-%s\n", GIT_TAG, GIT_REV);
	printf("GL Vendor  : %s\n", glGetString(GL_VENDOR) );
	printf("GL Renderer: %s\n", glGetString(GL_RENDERER) );
	printf("GL Version : %s\n", glGetString(GL_VERSION) );
	printf("SL Version : %s\n", glGetString(GL_SHADING_LANGUAGE_VERSION) );

	time_start = sys_time();

    return 0;   // it worked!
}


void main_end(void)
{

}


void main_loop(void)
{
	if(keys[KEY_ESCAPE])
	{
		killme=1;
	}

	time = (float)(sys_time() - time_start)/(float)sys_ticksecond;

	glClearColor(0.3f, 0.3f, 0.32f, 1.0f);
	glClear(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT);

}

